
spring:
  application:
    name: multiPlace
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: "jdbc:mysql://localhost:3306/multiPlace?allowPublicKeyRetrieval=true&useSSL=false&createDatabaseIfNotExist=true&serverTimezone=UTC&useUnicode=true&characterEncoding=UTF-8"
    username: ${db_username}
    password: ${db_password}
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
      properties:
        hibernate:
          format_sql: true
      defer-datasource-initialization: true

  mvc:
    hiddenmethod:
      filter:
        enabled: true

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.orm.jdbc.bind: TRACE
    org.springframework.security: TRACE

#    sql:
#      init:
#        mode: always

#    mvc:
#      hiddenmethod:
#        filter:
#          enabled: true

server:
  error:
    include-message: always
  #Cloudinary Properties
  #cloudinary:
  #api-key:
  #api-secret:
  #cloud-name:

app:
  default:
    password: qqq


binding-result-package: org.springframework.validation.BindingResult